# LAB 7 Task 4: Install Grafana

#- name: Install nessesary packages for grafana
#  apt: 
#    name: 
#      - apt-transport-https
#      - software-properties-common

- name: Add grafana gpg key
  apt_key: 
    url: https://packages.grafana.com/gpg.key
  
- name: Add grafana repo
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main

- name: Install 'grafana'
  apt: 
    name: grafana

- name: Copy grafana.ini.j2 to /etc/grafana/grafana.ini / reconfigure grafana
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: Restart grafana

- name: Start grafana
  service:
    name: grafana-server
    state: started
    enabled: yes


# LAB 7 Task 7: Configure Grafana provisioning

## Set admin password // Put into grafana.ini
#- name: Reset grafana admin password
# shell: grafana-cli admin reset-admin-password {{ grafana_admin_pass }}

## Configure Prometheus as default datasource
- name: Copy datasource.yaml to /etc/grafana/provisioning/datasources/
  template:
    src: datasource.yaml
    dest: /etc/grafana/provisioning/datasources/datasource.yaml
  notify: Restart grafana

## Configure Prometheus as default datasource
- name: Copy dashboard.yaml to /etc/grafana/provisioning/dashboards/
  template:
    src: dashboard.yaml
    dest: /etc/grafana/provisioning/dashboards/dashboard.yaml
  notify: Restart grafana


# LAB 7 Task 6: Create dashboard in Grafana

- name: Create directory for dashboard?
  file:
    path: /var/lib/grafana/dashboards
    state: directory
    mode: 0755

- name: Copy main.json to /var/lib/grafana/dashboards
  copy:
    src: main.json
    dest: /var/lib/grafana/dashboards/main.json
  notify: Restart grafana