# USERS


# Lab 2 Task 2- USER 1 with SSH key

- name: Add user 'juri' 
  ansible.builtin.user:
    name: hudolejev

- name: Set authorized keys taken from github keys 'juri'
  ansible.posix.authorized_key:
    user: hudolejev
    #state: present
    key: https://github.com/hudolejev.keys


# Lab 2 Task 2- USER 2 with SSH key

- name: Add user 'roman' 
  ansible.builtin.user:
    name: romankuchin

- name: Set authorized keys taken from github keys 'roman'
  ansible.posix.authorized_key:
    user: romankuchin
    #state: present
    key: https://github.com/romankuchin.keys