---
# LAB 3 Task 2 - uWSGI

- name: Install 'uwsgi'
  apt:
    name: uwsgi
    #state: latest
    #update_cache: yes //LAB 4 Task 3: Add the init role

- name: Install 'uwsgi-plugin-python3'
  apt:
    name: uwsgi-plugin-python3

- name: Ensure that uwsgi is started
  service:
    name: uwsgi
    state: started
    enabled: yes  

