# LAB 5 Task 2: Install Bind9 on vm2

- name: Install 'bind9'
  apt:
    name: bind9


## Task 3: Configure DNS forwarders
## Task 4: Configure access rules for DNS server

- name: Update named.conf.options
  template: 
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart bind9


## Task 5: Configure master zone
- name: Upload db.pho to /var/cache/bind/db.pho
  template: 
    src: db.pho
    dest: /var/cache/bind/db.pho

- name: Update named.conf.local
  template: 
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: 
    - Restart bind9
    - rndc reload


#- name: Get IP
#  debug:
#    msg: 
#      - bematv-1 IP is {{ hostvars['bematv-1']['ansible_default_ipv4']['address'] }}
#      - bematv-2 IP is {{ hostvars['bematv-2']['ansible_default_ipv4']['address'] }}


## Task 6: Update your VMs DNS settings

#- name: Update resolv.conf  ##I have created the resolver play for this
#  template: 
#    src: resolv.conf.j2
#    dest: /etc/resolv.conf
#  notify: 
#    - rndc reload
#    - Restart bind9

- name: Stop service systemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: Ensure bind9 is running
  service:
    name: bind9
    state: started