---
# LAB 2 Task 3: Create an Ansible role named nginx

- name: Install 'nginx'
  apt:
    name: nginx


# LAB 2 Task 3: Create an Ansible role named nginx

- name: Copy index.html to /var/www/html/index.html Replace the default HTML page
  copy:
    src: index.html
    dest: /var/www/html/index.html
    follow: no


# LAB 6 Task 3: Make Prometheus and Node Exporters available from outside
# LAB 7 Task 5: Configure reverse proxy

- name: Copy default.j2 to /etc/nginx/sites-enabled/default / Nginx as uWSGI frontend, Nginx configuration, Prometheus ports
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: Restart nginx

- name: Ensure nginx is started
  service:
    name: nginx
    state: started
    enabled: yes

