# LAB 6 Task 2: Install and configure Prometheus

- name: Install 'prometheus'
  apt:
    name: prometheus


  # LAB 6 Task 3: Make Prometheus and Node Exporters available from outside

- name: Copy prometheus.yml.j2 template
  template:
   src: prometheus.yml.j2
   dest: /etc/prometheus/prometheus.yml
  notify: Restart prometheus


  # LAB 6 Task 4: Adjust Prometheus service

- name: Copy prometheus.j2 template
  template:
   src: prometheus.j2
   dest: /etc/default/prometheus
  notify: Restart prometheus