---
# LAB 7 Task 3: Install Nginx exporter

- name: Install 'prometheus-nginx-exporter'
  apt:
    name: prometheus-nginx-exporter

- name: Copy exporter to /etc/nginx/sites-enabled/exporter / listen to stub status
  template:
    src: exporter
    dest: /etc/nginx/sites-enabled/exporter
  notify: 
    - Restart nginx # reload systemd is not enough
    - Restart nginx exporter
    - Reload daemons

- name: Execute handlers preemptively
  meta: flush_handlers

#- name: Sleep for 10 seconds and continue with play
#  wait_for:
#    timeout: 10

- name: Ensure nginx is started
  service:
    name: nginx
    state: started
    enabled: yes
  #become: yes

- name: Ensure nginx exporter is started
  service:
    name: prometheus-nginx-exporter
    state: started
    enabled: yes
  #become: yes
