---
# LAB7  Task 2: Install Bind9 exporter

- name: Install 'prometheus-bind-exporter'
  apt:
    name: prometheus-bind-exporter

- name: Ensure Bind9 exporter is started
  service:
    name: prometheus-bind-exporter
    state: started
    enabled: yes

