---
# LAB 12 Task 5

#- name: Resolver2
#  template: 
#    src: resolv.conf2.j2
#    dest: /etc/resolv.conf
#  notify: Resolver1
#  when: inventory_hostname == vm2

- name: Creating folder /opt/agama 
  file:
    path: /opt/agama
    state: directory

- name: Download agama container file
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
    dest: /opt/agama/Dockerfile

- name: Create agama docker image file
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

# LAB 12 --> 13
- name: Create agama Docker container 1
  community.docker.docker_container:
    name: agama-1
    image: agama
    env:
      AGAMA_DATABASE_URI: mysql+pymysql://{{ mysql_user }}:{{ mysql_user_pass }}@{{ mysql_host }}/{{ mysql_database }}
    published_ports: "{{ agama_port }}:8000"

# LAB 13 Task 1. Run Agama in Docker containers
- name: Create agama Docker container 2
  community.docker.docker_container:
    name: agama-2
    image: agama
    env:
      AGAMA_DATABASE_URI: mysql+pymysql://{{ mysql_user }}:{{ mysql_user_pass }}@{{ mysql_host }}/{{ mysql_database }}
    published_ports: "{{ agama_port + 1 }}:8000"

