# config file version
apiVersion: 1

datasources:
 - name: prometheus
   type: prometheus
#   orgId: 1
   url: http://{{ vm1 }}:9090/prometheus
   password:
   user:
   database:
   isDefault: true
   editable: true

 - name: InfluxDB
   type: influxdb
#   orgId: 1
   url: http://{{ vm1 }}.{{ domain }}:8086
   password:
   user:
   database: latency
   editable: true

 - name: InfluxDB-telegraf
   type: influxdb
#   orgId: 1
   url: http://{{ vm1 }}.{{ domain }}:8086
   password:
   user:
   database: telegraf
   editable: true
