{
 "title": "main",
 "time": { "from": "now-1m", "to": "now" },
 "panels": [
  { "title": "EXPORTERS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Exporter",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_exporter_build_info" }
   ]
  },
  {
   "title": "Bind Exporter",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_exporter_build_info" }
   ]
  },
  {
   "title": "Nginx Exporter",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginxexporter_build_info" }
   ]
  },
  {
   "title": "Influxdb Exporter",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_stats_exporter_build_info"
    }
   ]
  },
  {
   "title": "MySQL Exporter",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysqld_exporter_build_info" }
   ]
  },
  {
   "title": "HAProxy Exporter",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_exporter_build_info" }
   ]
  },
  { "title": "PINGER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Pinger Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "latency",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pinger Status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "latency",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dst" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "latency",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "HAPROXY & KEEPALIVED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Keepalived Master Slave Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "keepalived_vrrp_state" }
   ]
  },
  {
   "title": "Keepalived Health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_up" }
   ]
  },
  {
   "title": "HAProxy Frontend Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "haproxy_up" }
   ]
  },
  {
   "title": "HAProxy Backend Health",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "haproxy_server_up" }
   ]
  },
  { "title": "INFLUXDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Influxdb Health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success"
    }
   ]
  },
  {
   "title": "Influxdb Write Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(influxdb_write_write_ok[1m])"
    }
   ]
  },
  { "title": "NGINX", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Nginx Health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nginx_up" }
   ]
  },
  {
   "title": "Nginx HTTP Requests Per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])"
    }
   ]
  },
  { "title": "MYSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "MySQL Health",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "MySQL Commands Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total[1m])"
    }
   ]
  },
  {
   "title": "BIND9",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bind9 Health",
     "type": "stat",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 68 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "bind_up" }
     ]
    },
    {
     "title": "DNS Total Queries Per Minute",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 17, "x": 7, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(bind_resolver_queries_total[1m])"
      }
     ]
    }
   ]
  },
  { "title": "CPU & RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "CPU Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total[1m])"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prometheus_build_info" }
   ]
  },
  {
   "title": "RAM Active Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_memory_Active_bytes[1m])"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "grafana_build_info" }
   ]
  }
 ]
}