# LAB 8 Task 7: Add InfluxDB monitoring

- name: Download 'influxdb-stats-exporter'
  get_url:
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64
    dest: /usr/local/bin/
#    remote_src: yes

- name: Giving permission to influx_stats_exporter_linux_amd64
  file:
    path: /usr/local/bin/influx_stats_exporter_linux_amd64
    mode: 0755

- name: Making a service unit
  template:
    src: prometheus-influxdb-stats-exporter.service.j2
    dest: /etc/systemd/system/prometheus-influxdb-stats-exporter.service
    owner: prometheus
    group: prometheus
  notify:
    - Restart prometheus-influxdb-stats-exporter
    - Reload systemd

- name: Execute handlers preemptively
  meta: flush_handlers

- name: Ensure influxdb-stats-exporter is running
  service:
    name: prometheus-influxdb-stats-exporter
    state: started
    enabled: true