{
 "title": "main",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "keepalived_vrrp_state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "keepalived_vrrp_state" }
   ]
  },
  {
   "title": "haproxy_server_up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "haproxy_server_up" }
   ]
  },
  {
   "title": "haproxy_up ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "haproxy_up" }
   ]
  },
  {
   "title": "InfluxDB write rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(influxdb_write_write_ok[1m])"
    }
   ]
  },
  {
   "title": "InfluxDB health ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(influxdb_exporter_stats_query_success[1m])"
    }
   ]
  },
  {
   "title": "Nginx status + amount of requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "rate(nginx_up[1m])" },
    {
     "expr": "rate(nginx_http_requests_total[1m])"
    }
   ]
  },
  {
   "title": "MySQL status + amount of selects per minute ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "rate(mysql_up[1m])" },
    {
     "expr": "rate(mysql_global_status_commands_total[1m])"
    }
   ]
  },
  {
   "title": "Bind9 status + amount of A DNS queries per minute ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    { "expr": "rate(bind_up[1m])" },
    {
     "expr": "rate(bind_resolver_queries_total[1m])"
    }
   ]
  },
  {
   "title": "Memory consumption on VMs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "rate(node_memory_MemTotal_bytes[1m])"
    },
    {
     "expr": "rate(node_memory_MemFree_bytes[1m])"
    },
    {
     "expr": "rate(node_memory_Buffers_bytes[1m])"
    },
    {
     "expr": "rate(node_memory_Cached_bytes[1m])"
    },
    {
     "expr": "rate(node_memory_Active_bytes[1m])"
    }
   ]
  },
  {
   "title": "CPU load on VMs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total[1m])"
    }
   ]
  }
 ]
}