# LAB 3 Task 1: AGAMA the application

- name: Add the user 'agama'
  user:
    name: agama
    #system: yes
    #state: present

- name: Create install directory /opt/agama
  file:
    state: directory
    path: /opt/agama
    owner: agama
    mode: 0755

- name: Install 'python3-flask-sqlalchemy'
  apt: 
    name: python3-flask-sqlalchemy
#    state: latest
#    update_cache: yes #LAB 4 Task 3: Add the init role


# LAB 4 Task 9: Reconfigure AGAMA to use MySQL

- name: Install 'python3-pymysql'
  apt: 
    name: python3-pymysql 
    state: latest


# LAB 3 Task 1: AGAMA the application

- name: Download 'agama.py'
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama/agama.py
    mode: 0644