---

# LAB 5 Gather facts
- name: Collect info about all VMs
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - setup:
  tags:
    - SETUP
    - se


# LAB 4
- name: Init
  hosts: init
  gather_facts: no
  become: yes
  roles:
    - init
    #- backup # LAB 9 Task 2
  tags:
    - INIT
    - in


# LAB 9 Task 2
- name: Backup
  hosts: backup
  gather_facts: no
  become: yes
  roles:
    - backup # LAB 9 Task 2
  tags:
    - BACKUP
    - ba


# LAB 12 HOTFIX
- name: IPtables
  hosts: iptables
  gather_facts: no
  become: yes
  roles:
    - iptables
  tags:
    - IPTABLES
    - ip


# LAB 5
- name: Bind9 DNS server
  hosts: dns_servers
  gather_facts: no
  become: yes
  roles:
    - bind
    #- bind_exporter # LAB7 Task 2: Install Bind9 exporter
  tags:
    - BIND
    - bi


# MY OWN PROJECT // you have to change the resolver file in each vm.  have created this role to update the resolver in bematv-1 as well
- name: Resolver
  hosts: resolver
  gather_facts: no
  become: yes
  roles:
    - resolver
  tags:
    - RESOLVER
    - re


# LAB 4 Task 4: Install MySQL server
- name: Mysql database server
  hosts: db_servers
  gather_facts: no
  become: yes
  roles:
    - mysql
    - mysql_backup # LAB 10 Task 1
    #- mysql_exporter # LAB 7 Task 1: Install MySQL exporter
  tags:
    - MYSQL
    - my


# LAB 6 Task 1: Install Node Exporters
#- name: Node exporter
#  hosts: all
#  gather_facts: no
#  become: yes
#  roles:
#    - node_exporter


# LAB 12 Task 1: Install docker
- name: Docker
  hosts: docker
  gather_facts: no
  become: yes
  roles:
    - docker
  tags:
    - DOCKER
    - do

  
# LAB 7 install nginx in both machines
- name: Nginx
  hosts: nginx
  gather_facts: no
  become: yes
  roles:
    - nginx
    #- nginx_exporter # LAB 7 Task 3: Install Nginx exporter
  tags:
    - NGINX
    - ng


# LAB 1,2,3
- name: Agama web server
  hosts: web_servers
  gather_facts: no
  become: yes
  roles:
    #- users # LAB 4
    - agama
    - uwsgi
    #- nginx # LAB 7
  tags:
    - WEB_SERVERS
    - we

 
# LAB 6 Task 2: Install and configure Prometheus
- name: Prometheus
  hosts: prometheus
  gather_facts: no
  become: yes
  roles:
    - prometheus
  tags:
    - PROMETHEUS
    - pr      
      

# LAB 8
- name: InfluxDB and Telegraf
  hosts: influxdb
  gather_facts: no
  become: yes
  roles:
    - influxdb
    - influxdb_backup
  tags:
    - INFLUXDB
    - in

      
- name: Pinger
  hosts: pinger
  gather_facts: no
  become: yes
  roles:
    - pinger
  tags:
    - PINGER
    - pi
  

- name: Rsyslog
  hosts: rsyslog
  gather_facts: no
  become: yes
  roles:
    - rsyslog
  tags:
    - RSYSLOG
    - rs
    

# MY OWN PROJECT FOR EXPORTERS
- name: vm1 exporters
  hosts: vm1_exporters
  gather_facts: no
  become: yes
  roles:
    - node_exporter # LAB 6 Task 1: Install Node Exporters
    - nginx_exporter # LAB 7 Task 3: Install Nginx exporter
    - bind_exporter # LAB 14
    - influxdb_exporter
    - mysql_exporter # LAB 11 Task 1?
    - keepalived_exporter
    - haproxy_exporter
  tags:
    - VM1_EXPORTERS
    - vm1


- name: vm2 exporters
  hosts: vm2_exporters
  gather_facts: no
  become: yes
  roles:
    - node_exporter # LAB 6 Task 1: Install Node Exporters
    - nginx_exporter # LAB 7 Task 3: Install Nginx exporter
    - bind_exporter # LAB7 Task 2: Install Bind9 exporter
    - mysql_exporter # LAB 7 Task 1: Install MySQL exporter
    - keepalived_exporter
    - haproxy_exporter
  tags:
    - VM2_EXPORTERS
    - vm2


# LAB 7 Task 4: Install Grafana
- name: Grafana
  hosts: grafana
  gather_facts: no
  become: yes
  roles:
    - grafana
  tags:
    - GRAFANA
    - gr


- name: Keepalived
  hosts: keepalived
  gather_facts: yes
  become: yes
  roles:
    - keepalived
  tags:
    - KEEPALIVED
    - ke

- name: Haproxy
  hosts: haproxy
  gather_facts: yes
  become: yes
  roles:
    - haproxy
  tags:
    - HAPROXY
    - ha


