- name: Stop service systemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: Update resolv.conf
  template: 
    src: resolv.conf.j2
    dest: /etc/resolv.conf
  notify: rndc reload