---
# LAB 13 Task 4. Add HAProxy monitoring
- name: Install 'prometheus-haproxy-exporter'
  apt:
    name:
      - prometheus-haproxy-exporter

- name: Copy prometheus-haproxy-exporter
  template:
    src: prometheus-haproxy-exporter.j2
    dest: /etc/default/prometheus-haproxy-exporter
  notify: Restart haproxy-exporter

- name: Ensure haproxy exporter is started
  service:
    name: prometheus-haproxy-exporter
    state: started
